In [82]:
import pandas as pd
import numpy as np

In [83]:
# Load datasets

df_2021 = pd.read_csv("data/tn_2021_results.csv")
df_2026 = pd.read_csv("data/tn_2026_results.csv")
constituency_df = pd.read_csv("data/constituency_master.csv")

In [84]:
# Check Shape
print("2021 Shape:", df_2021.shape)
print("2026 Shape:", df_2026.shape)
print("Constituency Shape:", constituency_df.shape)

2021 Shape: (4232, 8)
2026 Shape: (4257, 8)
Constituency Shape: (234, 5)

In [85]:
df_2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro

In [86]:
df_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro

In [87]:
constituency_df.head()

   ac_number  constituency    district         region reserved
0          1  Gummidipundi  Tiruvallur  Chennai Metro      GEN
1          2       Ponneri  Tiruvallur  Chennai Metro       SC
2          3     Tiruttani  Tiruvallur  Chennai Metro      GEN
3          4   Thiruvallur  Tiruvallur  Chennai Metro      GEN
4          5   Poonamallee  Tiruvallur  Chennai Metro       SC

In [88]:
df_2021.columns

Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region'],
      dtype='object')

In [89]:
df_2026.columns

Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region'],
      dtype='object')

In [90]:
constituency_df.columns

Index(['ac_number', 'constituency', 'district', 'region', 'reserved'], dtype='object')

In [91]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4232 entries, 0 to 4231
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4232 non-null   object
 1   ac_number     4232 non-null   int64
 2   candidate     4232 non-null   object
 3   party         4232 non-null   object
 4   votes         4232 non-null   int64
 5   turnout       4232 non-null   float64
 6   reserved      4232 non-null   object
 7   region        4232 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 264.6+ KB

In [92]:
df_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4257 non-null   object
 1   ac_number     4257 non-null   int64
 2   candidate     4257 non-null   object
 3   party         4257 non-null   object
 4   votes         4257 non-null   int64
 5   turnout       0 non-null      float64
 6   reserved      4257 non-null   object
 7   region        4257 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 266.2+ KB

In [93]:
constituency_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ac_number     234 non-null    int64
 1   constituency  234 non-null    object
 2   district      234 non-null    object
 3   region        234 non-null    object
 4   reserved      234 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.3+ KB

In [94]:
df_2021.isnull().sum()

constituency    0
ac_number       0
candidate       0
party           0
votes           0
turnout         0
reserved        0
region          0
dtype: int64

In [95]:
df_2026.isnull().sum()

constituency       0
ac_number          0
candidate          0
party              0
votes              0
turnout         4257
reserved           0
region             0
dtype: int64

In [96]:
df_2021.duplicated().sum()    #Check Duplicate Rows

0

In [97]:
df_2026.duplicated().sum()  #Check Duplicate Rows

0

In [98]:
df_2026['party'].unique()

array(['TVK', 'AIADMK', 'DMK', 'NTK', 'NOTA', 'Bahujan Samaj Party',
       'Aanaithinthiya Jananayaka Pathukappu Kazhagam', 'IND',
       'Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi', 'INC',
       'Tamizhaga Murpokku Makkal Katchi', 'Desiya Makkal Sakthi Katchi',
       'Vanchit Bahujan Aaghadi', 'Tamizhaga Vaazhvurimai Katchi', 'DMDK',
       'Thakkam Katchi', 'Republican Party of India (Athawale)', 'AMMK',
       'BJP', 'All India Puratchi Thalaivar Makkal Munnettra Kazhagam',
       'Anti Corruption Dynamic Party', 'Samaniya Makkal Nala Katchi',
       'Anna Puratchi Thalaivar Amma Dravida Munnetra Kazhagam',
       'Naam Indiar Party', 'Naadaalum Makkal Katchi',
       'Anna MGR Dravida Makkal Kalgam', 'PMK',
       'Nationalist Janshakti Party', 'India Suyarajya Party', 'CPI(M)',
       'Democratic National Allegiance', 'Makkal Nalvaazhvuk Katchi',
       'Socialist Unity Centre Of India (COMMUNIST)', 'Samata Party',
       'All India Jananayaka Makkal Kazhagam', 'Makkal Murasu Katchi',
       'Tamilnadu Mahatma Gandhi Makkal Katchi', 'Makkalatchi Katchi',
       'Tamil Telugu National Party', 'National Maha Sabha Party',
       'Thamizhaga Munnetra Congress', 'MGR Makkal Katchi',
       'Jebamani Janata', 'Thamizhaga Dravidar Katchi',
       'Proutist Sarva Samaj', 'Dravida Jananayaga Makkal Katchi',
       'Puthiya Tamilagam', 'Indhu Dravida Makkal Katchi',
       'Communist Party of India (Marxist-Leninist) (Liberation)',
       'Anaithinthiya Anna Dravida Makkal Seyal katchi', 'VCK',
       'Mannin Maithargal Kazhagam',
       'Tamil Manila Murpokku Dravida Kazhagam',
       'Tamil Nadu Ilangyar Katchi',
       'Party for the Rights of Other backward Classes',
       'Viro Ke Vir Indian Party', "ALL PENSIONER'S PARTY",
       'Namadhu Makkal Katchi', 'IUML', 'Makkal Arasial Katchi',
       'Indian National League', 'All India Majlis-E-Inquilab-E-Millat',
       'All India Youth Development Party',
       'All India Uzhavargal Uzhaippalargal Katchi',
       'Makkal Nala Kazhagam', 'Bharat Jan Chikitsa Party',
       'Periyar Ambedkar Munnetra Kazhagam (PAMK)',
       'Vishwa Tamil Kazhagam', 'Tamilar Makkal Katchi', 'CPI',
       'Anna Makkal Katchi', 'Makkal Sananayaga Kudiyarasu Katchi',
       'Thamizhaka Padaippalar Makkal Katchi',
       'Anaithindia Samudaya Munnetra Kazhagam',
       'Indhia Kudiarasu Katchi', 'MAKKAL SAKTHI KATCHI',
       'Parivartan Rajniti Party', 'Vada Tamil Nadu Munnetra Katchi',
       'Ganasangam Party of India', 'Ahimsa Socialist Party',
       'Makkal Munnetra Katchi', 'Tamilaga Makkal Nala Katchi',
       'Namathu Kongu Munnetra Kalagam', 'All India Forward Bloc',
       "New Generation People's Party", 'Rashtriya Samaj Dal (R)',
       'Republican Party of India (A)', 'Viduthalai Kalam Katchi',
       'Akila Inthiya Makkal Marumalarchi Kazhakam',
       'Vidial Valarchi Perani', 'Thamizh Perarasu Katchi',
       'Bahujan Dravida Party', 'Our Mahathma National Party',
       'Thamizh Desiya Munnetra Kazhagam', 'Republican Party of India',
       'Ezhuchi Tamilargal Munnetra Kazhagam',
       'Ahila India Dhayaga Makkal Munnetra Katchi',
       'Communist Party of India (Marxist-Leninist) Red Star',
       'Puthiya Makkal Tamil Desam Katchi',
       'Nam Naadu Nam Makkal Nam Ethirkaalam Katchi',
       'Desa Makkal Munnetrak Kazhagam', 'Bharatha Makkal Katchi',
       'Kamarajar Deseeya Congress', 'Rashtriya Janata Dal',
       'Indian Christian Front'], dtype=object)

In [99]:
df_2026['region'].value_counts()

region
South            1001
Central           747
Chennai Metro     727
Kongu             634
North             621
Delta             527
Name: count, dtype: int64

In [100]:
df_2021.describe()

         ac_number          votes      turnout
count  4232.000000    4232.000000  4232.000000
mean    115.253544   10925.447070    73.038514
std      68.316849   27152.954736     7.726449
min       1.000000       2.000000    55.510000
25%      56.000000     121.000000    68.080000
50%     116.000000     336.500000    74.770000
75%     177.000000    1966.500000    78.850000
max     234.000000  171558.000000    87.370000

In [101]:
df_2026.describe()

         ac_number          votes  turnout
count  4257.000000    4257.000000      0.0
mean    112.949965   11586.591731      NaN
std      68.293502   25786.948660      NaN
min       1.000000       2.000000      NaN
25%      54.000000     122.000000      NaN
50%     113.000000     271.000000      NaN
75%     172.000000    1031.000000      NaN
max     234.000000  220382.000000      NaN

In [102]:
# Remove extra spaces from column names

df_2021.columns = df_2021.columns.str.strip()
df_2026.columns = df_2026.columns.str.strip()
constituency_df.columns = constituency_df.columns.str.strip()

In [103]:
# Standardize text columns

df_2021['party'] = df_2021['party'].str.strip().str.upper()
df_2026['party'] = df_2026['party'].str.strip().str.upper()

df_2021['constituency'] = df_2021['constituency'].str.strip()
df_2026['constituency'] = df_2026['constituency'].str.strip()

In [104]:
# Check unique parties

sorted(df_2026['party'].unique())

['AANAITHINTHIYA JANANAYAKA PATHUKAPPU KAZHAGAM',
 'AHILA INDIA DHAYAGA MAKKAL MUNNETRA KATCHI',
 'AHIMSA SOCIALIST PARTY',
 'AIADMK',
 'AKILA INTHIYA MAKKAL MARUMALARCHI KAZHAKAM',
 'ALL INDIA FORWARD BLOC',
 'ALL INDIA JANANAYAKA MAKKAL KAZHAGAM',
 'ALL INDIA MAJLIS-E-INQUILAB-E-MILLAT',
 'ALL INDIA PURATCHI THALAIVAR MAKKAL MUNNETTRA KAZHAGAM',
 'ALL INDIA UZHAVARGAL UZHAIPPALARGAL KATCHI',
 'ALL INDIA YOUTH DEVELOPMENT PARTY',
 "ALL PENSIONER'S PARTY",
 'AMMK',
 'ANAITHINDIA SAMUDAYA MUNNETRA KAZHAGAM',
 'ANAITHINTHIYA ANNA DRAVIDA MAKKAL SEYAL KATCHI',
 'ANNA MAKKAL KATCHI',
 'ANNA MGR DRAVIDA MAKKAL KALGAM',
 'ANNA PURATCHI THALAIVAR AMMA DRAVIDA MUNNETRA KAZHAGAM',
 'ANTI CORRUPTION DYNAMIC PARTY',
 'BAHUJAN DRAVIDA PARTY',
 'BAHUJAN SAMAJ PARTY',
 'BHARAT JAN CHIKITSA PARTY',
 'BHARATHA MAKKAL KATCHI',
 'BJP',
 'COMMUNIST PARTY OF INDIA (MARXIST-LENINIST) (LIBERATION)',
 'COMMUNIST PARTY OF INDIA (MARXIST-LENINIST) RED STAR',
 'CPI',
 'CPI(M)',
 'DEMOCRATIC NATIONAL ALLEGIANCE',
 'DESA MAKKAL MUNNETRAK KAZHAGAM',
 'DESIYA MAKKAL SAKTHI KATCHI',
 'DMDK',
 'DMK',
 'DRAVIDA JANANAYAGA MAKKAL KATCHI',
 'EZHUCHI TAMILARGAL MUNNETRA KAZHAGAM',
 'GANASANGAM PARTY OF INDIA',
 'INC',
 'IND',
 'INDHIA KUDIARASU KATCHI',
 'INDHU DRAVIDA MAKKAL KATCHI',
 'INDIA SUYARAJYA PARTY',
 'INDIAN CHRISTIAN FRONT',
 'INDIAN NATIONAL LEAGUE',
 'IUML',
 'JEBAMANI JANATA',
 'KAMARAJAR DESEEYA CONGRESS',
 'MAKKAL ARASIAL KATCHI',
 'MAKKAL MUNNETRA KATCHI',
 'MAKKAL MURASU KATCHI',
 'MAKKAL NALA KAZHAGAM',
 'MAKKAL NALVAAZHVUK KATCHI',
 'MAKKAL SAKTHI KATCHI',
 'MAKKAL SANANAYAGA KUDIYARASU KATCHI',
 'MAKKALATCHI KATCHI',
 'MANNIN MAITHARGAL KAZHAGAM',
 'MGR MAKKAL KATCHI',
 'NAADAALUM MAKKAL KATCHI',
 'NAAM INDIAR PARTY',
 'NAM NAADU NAM MAKKAL NAM ETHIRKAALAM KATCHI',
 'NAMADHU MAKKAL KATCHI',
 'NAMATHU KONGU MUNNETRA KALAGAM',
 'NATIONAL MAHA SABHA PARTY',
 'NATIONALIST JANSHAKTI PARTY',
 "NEW GENERATION PEOPLE'S PARTY",
 'NOTA',
 'NTK',
 'OUR MAHATHMA NATIONAL PARTY',
 'PARIVARTAN RAJNITI PARTY',
 'PARTY FOR THE RIGHTS OF OTHER BACKWARD CLASSES',
 'PERIYAR AMBEDKAR MUNNETRA KAZHAGAM (PAMK)',
 'PMK',
 'PROUTIST SARVA SAMAJ',
 'PUTHIYA MAKKAL TAMIL DESAM KATCHI',
 'PUTHIYA TAMILAGAM',
 'RASHTRIYA JANATA DAL',
 'RASHTRIYA SAMAJ DAL (R)',
 'REPUBLICAN PARTY OF INDIA',
 'REPUBLICAN PARTY OF INDIA (A)',
 'REPUBLICAN PARTY OF INDIA (ATHAWALE)',
 'SAMANIYA MAKKAL NALA KATCHI',
 'SAMATA PARTY',
 'SOCIALIST UNITY CENTRE OF INDIA (COMMUNIST)',
 'TAMIL MANILA MURPOKKU DRAVIDA KAZHAGAM',
 'TAMIL NADU ILANGYAR KATCHI',
 'TAMIL TELUGU NATIONAL PARTY',
 'TAMILAGA MAKKAL NALA KATCHI',
 'TAMILAR MAKKAL KATCHI',
 'TAMILNADU MAHATMA GANDHI MAKKAL KATCHI',
 'TAMIZHAGA MURPOKKU MAKKAL KATCHI',
 'TAMIZHAGA VAAZHVURIMAI KATCHI',
 'THAKKAM KATCHI',
 'THAMIZH DESIYA MUNNETRA KAZHAGAM',
 'THAMIZH PERARASU KATCHI',
 'THAMIZHAGA DRAVIDAR KATCHI',
 'THAMIZHAGA MUNNETRA CONGRESS',
 'THAMIZHAKA PADAIPPALAR MAKKAL KATCHI',
 'TVK',
 'VADA TAMIL NADU MUNNETRA KATCHI',
 'VANCHIT BAHUJAN AAGHADI',
 'VCK',
 'VEERATH THIYAGI VISWANATHADOSS THOZHILALARKAL KATCHI',
 'VIDIAL VALARCHI PERANI',
 'VIDUTHALAI KALAM KATCHI',
 'VIRO KE VIR INDIAN PARTY',
 'VISHWA TAMIL KAZHAGAM']

In [105]:
# Verify unique constituencies

print(df_2021['ac_number'].nunique())
print(df_2026['ac_number'].nunique())

234
234

In [106]:
df_2026['reserved'].value_counts()

reserved
GEN    3599
SC      631
ST       27
Name: count, dtype: int64

In [107]:
df_2026['region'].value_counts()

region
South            1001
Central           747
Chennai Metro     727
Kongu             634
North             621
Delta             527
Name: count, dtype: int64

In [108]:
# Constituency-level reservation distribution

df_2026[['ac_number', 'reserved']].drop_duplicates()['reserved'].value_counts()

reserved
GEN    188
SC      44
ST       2
Name: count, dtype: int64

In [109]:
# Sort candidates by votes within each constituency

df_2021_sorted = df_2021.sort_values(
    ['ac_number', 'votes'],
    ascending=[True, False]
)

df_2026_sorted = df_2026.sort_values(
    ['ac_number', 'votes'],
    ascending=[True, False]
)

In [110]:
# Rank candidates within each constituency

df_2021_sorted['rank'] = (
    df_2021_sorted
    .groupby('ac_number')['votes']
    .rank(method='first', ascending=False)
)

df_2026_sorted['rank'] = (
    df_2026_sorted
    .groupby('ac_number')['votes']
    .rank(method='first', ascending=False)
)

In [111]:
# Convert rank column to integer

df_2021_sorted['rank'] = df_2021_sorted['rank'].astype(int)
df_2026_sorted['rank'] = df_2026_sorted['rank'].astype(int)

In [112]:
df_2021_sorted.head(10)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,rank
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro,1
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro,2
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro,3
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro,4
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro,5
5,Gummidipundi,1,NAGARAJ S,BSP,1038,78.08,GEN,Chennai Metro,6
6,Gummidipundi,1,SARAVANAN V,IJK,816,78.08,GEN,Chennai Metro,7
7,Gummidipundi,1,SARAVANAN E,IND,532,78.08,GEN,Chennai Metro,8
8,Gummidipundi,1,DEVANATHAN R,IND,482,78.08,GEN,Chennai Metro,9
9,Gummidipundi,1,LAKSHMI R,IND,374,78.08,GEN,Chennai Metro,10

In [113]:
# Extract winners (rank = 1)

winners_2021 = df_2021_sorted[
    df_2021_sorted['rank'] == 1
]

winners_2026 = df_2026_sorted[
    df_2026_sorted['rank'] == 1
]

In [114]:
winners_2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,rank
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro,1
13,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro,1
24,Tiruttani,3,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro,1
39,Thiruvallur,4,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro,1
51,Poonamallee,5,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro,1

In [115]:
winners_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,rank
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro,1
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro,1
30,Tiruttani,3,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro,1
44,Thiruvallur,4,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro,1
59,Poonamallee,5,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro,1

In [116]:
# Verify row count

print(winners_2021.shape)
print(winners_2026.shape)

(234, 9)
(234, 9)

In [117]:
# Extract runner-ups (rank = 2)

runners_2021 = df_2021_sorted[
    df_2021_sorted['rank'] == 2
]

runners_2026 = df_2026_sorted[
    df_2026_sorted['rank'] == 2
]

In [118]:
# Verify runner-ups

runners_2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,rank
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro,2
14,Ponneri,2,BALARAMAN. P,AIADMK,84839,78.20,SC,Chennai Metro,2
25,Tiruttani,3,G.Hari,AIADMK,91061,78.76,GEN,Chennai Metro,2
40,Thiruvallur,4,"RAMANAH, BE VEE",AIADMK,85008,77.20,GEN,Chennai Metro,2
52,Poonamallee,5,Rajamannar S X,PMK,55468,72.99,SC,Chennai Metro,2

In [119]:
turnout_df = pd.read_excel("data/turnout_2026.xlsx")
df_2026 = df_2026.drop(columns=['turnout'])

In [120]:
df_2026 = df_2026.merge(
    turnout_df,
    on='ac_number',
    how='left'
)

In [121]:
df_2026[['ac_number', 'turnout']].head()

   ac_number  turnout
0          1    91.48
1          1    91.48
2          1    91.48
3          1    91.48
4          1    91.48

In [122]:
winners_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,rank
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro,1
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro,1
30,Tiruttani,3,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro,1
44,Thiruvallur,4,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro,1
59,Poonamallee,5,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro,1

In [126]:
# Re-sort updated dataframe

df_2026_sorted = df_2026.sort_values(
    ['ac_number', 'votes'],
    ascending=[True, False]
)

In [127]:
# Recreate rank column

df_2026_sorted['rank'] = (
    df_2026_sorted
    .groupby('ac_number')['votes']
    .rank(method='first', ascending=False)
    .astype(int)
)

In [128]:
# Recreate winners table

winners_2026 = df_2026_sorted[
    df_2026_sorted['rank'] == 1
]

In [129]:
winners_2026.head()

,constituency,ac_number,candidate,party,votes,reserved,region,turnout,rank
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,GEN,Chennai Metro,91.48,1
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,SC,Chennai Metro,90.21,1
30,Tiruttani,3,G.HARI,AIADMK,89169,GEN,Chennai Metro,90.97,1
44,Thiruvallur,4,DR. T. ARUNKUMAR,TVK,92190,GEN,Chennai Metro,90.17,1
59,Poonamallee,5,PRAKASAM.R,TVK,161309,SC,Chennai Metro,83.78,1

# Final Constituency Summary Table

In [130]:
# Select winner columns

winners_2021 = winners_2021[[
    'ac_number',
    'constituency',
    'candidate',
    'party',
    'votes',
    'turnout',
    'region',
    'reserved'
]]

winners_2026 = winners_2026[[
    'ac_number',
    'constituency',
    'candidate',
    'party',
    'votes',
    'turnout',
    'region',
    'reserved'
]]

In [131]:
# Rename winner columns

winners_2021.columns = [
    'ac_number',
    'constituency',
    'winner_candidate',
    'winner_party',
    'winner_votes',
    'turnout',
    'region',
    'reserved'
]

winners_2026.columns = [
    'ac_number',
    'constituency',
    'winner_candidate',
    'winner_party',
    'winner_votes',
    'turnout',
    'region',
    'reserved'
]

In [132]:
# Select runner-up columns

runners_2021 = runners_2021[[
    'ac_number',
    'candidate',
    'party',
    'votes'
]]

runners_2026 = runners_2026[[
    'ac_number',
    'candidate',
    'party',
    'votes'
]]

In [133]:
# Rename runner-up columns

runners_2021.columns = [
    'ac_number',
    'runner_candidate',
    'runner_party',
    'runner_votes'
]

runners_2026.columns = [
    'ac_number',
    'runner_candidate',
    'runner_party',
    'runner_votes'
]

In [134]:
# Merge winners and runner-ups

summary_2021 = winners_2021.merge(
    runners_2021,
    on='ac_number'
)

summary_2026 = winners_2026.merge(
    runners_2026,
    on='ac_number'
)

In [135]:
# Calculate victory margin

summary_2021['margin'] = (
    summary_2021['winner_votes']
    - summary_2021['runner_votes']
)

summary_2026['margin'] = (
    summary_2026['winner_votes']
    - summary_2026['runner_votes']
)

In [136]:
summary_2026.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,turnout,region,reserved,runner_candidate,runner_party,runner_votes,margin
0,1,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,91.48,Chennai Metro,GEN,SUDHAKAR.V,AIADMK,66375,27945
1,2,Ponneri,DR.RAVI.M.S,TVK,110439,90.21,Chennai Metro,SC,DURAI CHANDRASEKAR,INC,54671,55768
2,3,Tiruttani,G.HARI,AIADMK,89169,90.97,Chennai Metro,GEN,M.SATHYA KUMAR,TVK,83376,5793
3,4,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,90.17,Chennai Metro,GEN,V.G. RAAJENDRAN,DMK,67430,24760
4,5,Poonamallee,PRAKASAM.R,TVK,161309,83.78,Chennai Metro,SC,KRISHNASWAMY.A,DMK,88569,72740

###### Flip analysis helps identify constituencies
###### where the winning party changed between
###### 2021 and 2026 elections.
###### This helps analyze political shifts,
###### regional swings, and changing voter preferences.

In [137]:
# Select required columns

flip_2021 = summary_2021[[
    'ac_number',
    'constituency',
    'winner_party'
]]

flip_2026 = summary_2026[[
    'ac_number',
    'winner_party'
]]

In [138]:
# Rename columns

flip_2021.columns = [
    'ac_number',
    'constituency',
    'winner_2021'
]

flip_2026.columns = [
    'ac_number',
    'winner_2026'
]

In [139]:
# Merge both election years

flip_df = flip_2021.merge(
    flip_2026,
    on='ac_number'
)

In [141]:
# Create flip flag

flip_df['flipped'] = (
    flip_df['winner_2021'] != flip_df['winner_2026']
)

In [144]:
flip_df.head()

   ac_number  constituency winner_2021 winner_2026  flipped
0          1  Gummidipundi         DMK         TVK     True
1          2       Ponneri         INC         TVK     True
2          3     Tiruttani         DMK      AIADMK     True
3          4   Thiruvallur         DMK         TVK     True
4          5   Poonamallee         DMK         TVK     True

In [146]:
flip_df['flipped'].value_counts()  # Count total flipped seats.

flipped
True     163
False     71
Name: count, dtype: int64

In [147]:
# Count seats won by each party in 2021

party_2021 = (
    summary_2021['winner_party']
    .value_counts()
    .reset_index()
)

party_2021.columns = [
    'party',
    'seats_2021'
]

In [148]:
# Count seats won by each party in 2026

party_2026 = (
    summary_2026['winner_party']
    .value_counts()
    .reset_index()
)

party_2026.columns = [
    'party',
    'seats_2026'
]

In [149]:
# Merge both election results

party_comparison = party_2021.merge(
    party_2026,
    on='party',
    how='outer'
).fillna(0)

In [150]:
# Convert seat counts to integer

party_comparison['seats_2021'] = (
    party_comparison['seats_2021']
    .astype(int)
)

party_comparison['seats_2026'] = (
    party_comparison['seats_2026']
    .astype(int)
)

In [151]:
# Calculate seat gain/loss

party_comparison['seat_change'] = (
    party_comparison['seats_2026']
    - party_comparison['seats_2021']
)

In [152]:
# Sort by 2026 performance

party_comparison = (
    party_comparison
    .sort_values(
        by='seats_2026',
        ascending=False
    )
)

party_comparison

     party  seats_2021  seats_2026  seat_change
10     TVK           0         108          108
6      DMK         133          59          -74
0   AIADMK          66          47          -19
7      INC          18           5          -13
9      PMK           5           4           -1
3      CPI           2           2            0
4   CPI(M)           2           2            0
8     IUML           0           2            2
11     VCK           4           2           -2
1     AMMK           0           1            1
2      BJP           4           1           -3
5     DMDK           0           1            1

In [153]:
# Region-wise seat count for 2026

region_party_2026 = (
    summary_2026
    .groupby(['region', 'winner_party'])
    .size()
    .reset_index(name='seats')
)

region_party_2026.head()

    region winner_party  seats
0  Central       AIADMK     15
1  Central         DMDK      1
2  Central          DMK      8
3  Central          PMK      3
4  Central          TVK     12

In [154]:
# Sort for readability

region_party_2026 = (
    region_party_2026
    .sort_values(
        ['region', 'seats'],
        ascending=[True, False]
    )
)

region_party_2026

           region winner_party  seats
0         Central       AIADMK     15
4         Central          TVK     12
2         Central          DMK      8
3         Central          PMK      3
5         Central          VCK      2
1         Central         DMDK      1
8   Chennai Metro          TVK     29
7   Chennai Metro          DMK      2
6   Chennai Metro       AIADMK      1
13          Delta          DMK     14
16          Delta          TVK     10
9           Delta       AIADMK      4
10          Delta         AMMK      1
11          Delta          CPI      1
12          Delta       CPI(M)      1
14          Delta          INC      1
15          Delta         IUML      1
20          Kongu          TVK     16
19          Kongu          DMK      9
17          Kongu       AIADMK      7
18          Kongu          BJP      1
21          North       AIADMK     15
26          North          TVK     15
23          North          DMK      4
22          North          CPI      1
24          North         IUML      1
25          North          PMK      1
31          South          TVK     26
29          South          DMK     22
27          South       AIADMK      5
30          South          INC      4
28          South       CPI(M)      1

In [155]:
# Find top party in each region

regional_winner = (
    region_party_2026
    .sort_values(
        ['region', 'seats'],
        ascending=[True, False]
    )
    .drop_duplicates('region')
)

regional_winner

           region winner_party  seats
0         Central       AIADMK     15
8   Chennai Metro          TVK     29
13          Delta          DMK     14
20          Kongu          TVK     16
21          North       AIADMK     15
31          South          TVK     26

In [156]:
# Top 10 closest contests in 2026

closest_seats = (
    summary_2026
    .sort_values('margin')
    .head(10)
)

closest_seats[[
    'constituency',
    'winner_party',
    'runner_party',
    'margin',
    'region'
]]

        constituency winner_party runner_party  margin   region
184      Tiruppattur          TVK          DMK       1    South
53      Veppanahalli          DMK       AIADMK     138    North
228    Kanniyakumari       AIADMK          DMK     214    South
65             Polur          TVK         DMDK     227    North
75      Tirukkoyilur       AIADMK          TVK     285  Central
94   Paramathi-Velur       AIADMK          DMK     308  Central
136       Kulithalai          DMK          TVK     579    Kongu
170       Kumbakonam          TVK          DMK     679    Delta
126           Palani       AIADMK          TVK     693    South
71        Tindivanam          VCK       AIADMK     734  Central

In [157]:
closest_seats = closest_seats.reset_index(drop=True)

closest_seats[[
    'constituency',
    'winner_party',
    'runner_party',
    'margin',
    'region'
]]

      constituency winner_party runner_party  margin   region
0      Tiruppattur          TVK          DMK       1    South
1     Veppanahalli          DMK       AIADMK     138    North
2    Kanniyakumari       AIADMK          DMK     214    South
3            Polur          TVK         DMDK     227    North
4     Tirukkoyilur       AIADMK          TVK     285  Central
5  Paramathi-Velur       AIADMK          DMK     308  Central
6       Kulithalai          DMK          TVK     579    Kongu
7       Kumbakonam          TVK          DMK     679    Delta
8           Palani       AIADMK          TVK     693    South
9       Tindivanam          VCK       AIADMK     734  Central

In [159]:
# Save processed datasets

summary_2021.to_csv(
    "data/summary_2021.csv",
    index=False
)

summary_2026.to_csv(
    "data/summary_2026.csv",
    index=False
)

flip_df.to_csv(
    "data/flip_analysis.csv",
    index=False
)

party_comparison.to_csv(
    "data/party_comparison.csv",
    index=False
)

region_party_2026.to_csv(
    "data/region_party_2026.csv",
    index=False
)

closest_seats.to_csv(
    "data/closest_contests.csv",
    index=False
)